-- Add new fields to Plan table
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxAdegas" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "annualDiscountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "features" JSONB;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "isHighlighted" BOOLEAN NOT NULL DEFAULT false;
